# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: andreislab01.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'andreislab01.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ndreislab01.proto\x12\x0c\x61ndreislab01\"N\n\nFitRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x03(\x02\x12\r\n\x05label\x18\x02 \x03(\x05\x12\x0f\n\x07x_shape\x18\x03 \x03(\x05\x12\x0f\n\x07y_shape\x18\x04 \x03(\x05\"\x1f\n\x0b\x46itResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\".\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\" \n\x0fPredictResponse\x12\r\n\x05label\x18\x01 \x03(\x05\x32\x9e\x01\n\x08MLServer\x12\x42\n\tServerFit\x12\x18.andreislab01.FitRequest\x1a\x19.andreislab01.FitResponse\"\x00\x12N\n\rServerPredict\x12\x1c.andreislab01.PredictRequest\x1a\x1d.andreislab01.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'andreislab01_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FITREQUEST']._serialized_start=36
  _globals['_FITREQUEST']._serialized_end=114
  _globals['_FITRESPONSE']._serialized_start=116
  _globals['_FITRESPONSE']._serialized_end=147
  _globals['_PREDICTREQUEST']._serialized_start=149
  _globals['_PREDICTREQUEST']._serialized_end=195
  _globals['_PREDICTRESPONSE']._serialized_start=197
  _globals['_PREDICTRESPONSE']._serialized_end=229
  _globals['_MLSERVER']._serialized_start=232
  _globals['_MLSERVER']._serialized_end=390
# @@protoc_insertion_point(module_scope)
